name: Build
run-name: Build solver
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - run: ls -al target/release

      - uses: actions/upload-artifact@v4
        with:
          name: solver
          path: target/release/cg_tsp.exe
