
name: test secret
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # ENV Vars
      - name: Test env
        env:
          FOO: ${{ secrets.foo }}
        run: |
          IFS=';' read -ra PARTS <<< "$FOO"
          echo "Second part: ${PARTS[1]}"
          # Loop through all parts
          for part in "${PARTS[@]}"; do
            echo "Part: $part"
          done
      # ENV Vars
      - name: Test env
        env:
          FOO: ${{ secrets.foo }}
        run: |
          echo "${FOO}"
      - name: Split secret into 'a' and 'b'
        env:
          BAR: ${{ secrets.bar }}
        run: |
          a="${BAR:0:1}"
          b="${BAR:1}"
          echo "$a"
          echo "$b"
          echo "${a}_$b"
          echo "${a}${b}"
