
name: test secret
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # ENV Vars
      - name: Test env
        env:
          FOO: ${{ secrets.foo }}
        run: |
          IFS=';' read -ra PARTS <<< "$FOO"
          echo "Second part: ${PARTS[1]}"
          # Loop through all parts
          for part in "${PARTS[@]}"; do
            echo "Part: $part"
          done